packages:
  - 'docs'
  - 'packages/*'
  - 'plugins/*'

allowBuilds:
  nx: false
  puppeteer: false
  unrs-resolver: false

minimumReleaseAge: 10080
blockExoticSubdeps: true
trustPolicy: no-downgrade

minimumReleaseAgeExclude:
  - "@qlik/*"
